### PR TITLE
Fix addons icon

### PR DESCRIPTION
**Pull request by Tianyou-Song**
The addons icon was bothering me.

Before:
image

After:
image

### CODE REVIEW

**Comment by jackyaz** [comment]
Which f/w versions have you tested this with please? The icon used to work previously.
From your screenshots it looks like you might be running a ROG/custom theme?

**Comment by Tianyou-Song** [comment]
Yeah it's the merlin's rog ui. Specifically, the new `GT-AXE16000_388.2_0_rog_nand_squashfs.pkgtb`

**Comment by maghuro** [comment]
Rog here on GT-AX6000.
I can confirm that the icon is buggy. This PR is needed.

**Comment by maghuro** [comment]
I think it didn't solved.
After update, rebooted router and same issue.

**Comment by jackyaz** [comment]
You need to be on the develop branch and force an update

**Comment by maghuro** [comment]
> You need to be on the develop branch and force an update

Done that. Develop branch, **uf** and same symptom 

Edit: uninstalled and installed again directly from develop branch solved the issue.

**Comment by jackyaz** [comment]
I just pushed an update to develop that will fix this for existing users

**Pull request merged**
