### PR TITLE
Changes/fixes to address missing temperatures on WebGUI, Tri-Band & Quad-Band temps.

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
- Added/modified code to address "missing temperature" values on the webGUI page.
- Added support for Tri-Band & Quad-Band routers when reporting temperatures on webGUI & CLI menu.
- Added/modified code to address issues with some webGUI elements (SiteMap & pop-ups) being left behind after uninstalling the add-on.

### CODE REVIEW

**Review by bhurg — APPROVED** [review]

**Comment by Martinski4GitHub** [comment]
Jack Yaz,

Here's a screenshot of what I'm seeing for PR #24:

scMerlin_PR#24

The only comment/review that I see is from user "**@bhurg**" from 2 weeks ago. I've also checked both the "**Files changed**" & "**Notifications**" panels and see no other comments or notifications for PR #24.

Can you point me to the GitHub panel section where I can view your comment?

Thanks.

**Comment by bhurg** [comment]
Hi Jack-

I believe I accidentally clicked to approve the changes and didn’t know how to withdraw it. My apologies!

**Comment by jackyaz** [comment]
> Jack Yaz,
> 
> Here's a screenshot of what I'm seeing for PR #24:
> 
> scMerlin_PR#24
> 
> The only comment/review that I see is from user "**@bhurg**" from 2 weeks ago. I've also checked both the "**Files changed**" & "**Notifications**" panels and see no other comments or notifications for PR #24.
> 
> Can you point me to the GitHub panel section where I can view your comment?
> 
> Thanks.

i've tried tagging you on the comment, hopefully that will appear otherwise I will DM you

**Comment by Martinski4GitHub** [comment]
> > Jack Yaz,
> > Here's a screenshot of what I'm seeing for PR #24:
> > ...
> > The only comment/review that I see is from user "**@bhurg**" from 2 weeks ago. I've also checked both the "**Files changed**" & "**Notifications**" panels and see no other comments or notifications for PR #24.
> > Can you point me to the GitHub panel section where I can view your comment?
> > Thanks.
> 
> i've tried tagging you on the comment, hopefully that will appear otherwise I will DM you
>
While in the break/snack room at work (grabbing a snack & a cup of coffee :>), I got your message and went to check - unfortunately, nothing has changed. The "**Conversation**" tab is not showing any additional comments except for your latest one that I'm responding to here. I even went to check on the "**Files changed**" tab and made sure that the option to "**Show comments**" was indeed checked/selected (just in case that's where your comment was) but no comments/reviews are visible at all.

scMerlin_PR#24_FilesChanged

I find it very strange that, AFAIK, I get all your other messages/comments here in the "**Conversation**" tab but, for some reason, one specific comment appears to be very elusive and wants to stay hidden from me. In any case, it sounds like a DM will be necessary (but I still wish to find out what the problem is).

**Comment by jackyaz** [comment]
It was only a minor comment:

image


servciename seems odd as temperature isn't a service really. but i may be splitting hairs!

**Comment by Martinski4GitHub** [comment]
> 
> 
> image
> 
> servciename seems odd as temperature isn't a service really. but i may be splitting hairs!
>
>

Ah yes, I see where that needs an explanation. The reason I replaced "**settingname**" with "**servicename**" for that particular line is that I needed more horizontal space when showing all temperatures for a quad-band router.

For example, here's a screenshot of a test showing "temperatures" for a quad-band router when using the "**settingname**" class setting:

scMerlin_Temps_QuadBand_Test1

And here's a screenshot of a test showing "temperatures" for a quad-band router when using the "**servicename**" class setting:

scMerlin_Temps_QuadBand_Test2

The 2nd screenshot shows that there's now ample room for the quad-band scenarios so it's better, IMO.

I suppose I could have defined another class (e.g. "**tempsname**") just for temperatures, but I didn't see a real need to have duplicate code just for this little detail, but if you want I can do that. Or, I could add a comment explaining why the change from "**settingname**" to "**servicename**" so that the reasoning is explicitly clear. Let me know what you would prefer.

**Comment by jackyaz** [comment]
Makes sense to me, thanks. Merged

**Pull request merged**
